import type { Metadata } from "next";
import { ClerkProvider } from "@clerk/nextjs";

import "./globals.css";
import { ThemeProvider } from "@/components/themeProvider";
import { dark } from "@clerk/themes";




export const metadata: Metadata = {
  title: "Twitch-clone",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider appearance={{baseTheme:dark}}>
    <html lang="en">
     
      <body >
      <ThemeProvider
       attribute="classs"
       forcedTheme="dark"
       storageKey="twich"
       >
        {children}
        </ThemeProvider>
        </body>
     
     
    </html>
    </ClerkProvider>
  );
}
